# Site settings
name: 做梦人
email: 529961107@qq.com
author: 一直往前走
url: 
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/makui123/
baseurl: ""
description: Actually, less is more!
meta_description: 种一棵树，最好的时间是十年前，然后是现在。
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: makui123

# Build settings
markdown: kramdown

